package com.nammashale.inventory.domain.usecase

import com.nammashale.inventory.domain.model.Asset
import com.nammashale.inventory.domain.model.AssetCondition
import com.nammashale.inventory.domain.model.DashboardStats
import com.nammashale.inventory.utils.DateUtils
import javax.inject.Inject

/**
 * Generates a plain-text summary report of the school's asset inventory.
 * Can be copied to clipboard or shared as a text file.
 */
class GenerateReportUseCase @Inject constructor() {

    operator fun invoke(assets: List<Asset>, stats: DashboardStats): String {
        val sb = StringBuilder()
        val divider = "─".repeat(40)

        sb.appendLine("╔══════════════════════════════════════════╗")
        sb.appendLine("║   NAMMA-SHAALE INVENTORY REPORT          ║")
        sb.appendLine("║   Digital Asset Auditor for Schools      ║")
        sb.appendLine("╚══════════════════════════════════════════╝")
        sb.appendLine()
        sb.appendLine("Generated on: ${DateUtils.formatDateTime(System.currentTimeMillis())}")
        sb.appendLine()

        // Summary stats
        sb.appendLine("📊 SUMMARY STATISTICS")
        sb.appendLine(divider)
        sb.appendLine("  Total Assets       : ${stats.totalAssets}")
        sb.appendLine("  ✅ Working         : ${stats.workingCount}")
        sb.appendLine("  ⚠️  Needs Repair   : ${stats.needsRepairCount}")
        sb.appendLine("  ❌ Broken          : ${stats.brokenCount}")
        sb.appendLine("  Health Score       : ${"%.1f".format(stats.healthPercentage)}%")
        sb.appendLine()

        // Condition breakdown
        sb.appendLine("📋 FULL ASSET LIST")
        sb.appendLine(divider)

        val grouped = assets.groupBy { it.condition }

        // Show broken first (most urgent)
        listOf(AssetCondition.BROKEN, AssetCondition.NEEDS_REPAIR, AssetCondition.WORKING)
            .forEach { condition ->
                val group = grouped[condition] ?: emptyList()
                if (group.isNotEmpty()) {
                    sb.appendLine()
                    sb.appendLine("── ${condition.label.uppercase()} (${group.size}) ──")
                    group.forEachIndexed { idx, asset ->
                        sb.appendLine("  ${idx + 1}. ${asset.name}")
                        sb.appendLine("     Serial  : ${asset.serialNumber.ifBlank { "N/A" }}")
                        sb.appendLine("     Location: ${asset.location.ifBlank { "Not specified" }}")
                        sb.appendLine("     Added   : ${DateUtils.formatDate(asset.dateAdded)}")
                        if (asset.description.isNotBlank()) {
                            sb.appendLine("     Notes   : ${asset.description}")
                        }
                    }
                }
            }

        sb.appendLine()
        sb.appendLine(divider)
        sb.appendLine("RECOMMENDATIONS:")
        if (stats.brokenCount > 0) {
            sb.appendLine("  ⚠ ${stats.brokenCount} asset(s) are broken — immediate action required.")
        }
        if (stats.needsRepairCount > 0) {
            sb.appendLine("  🔧 ${stats.needsRepairCount} asset(s) need repair — schedule maintenance.")
        }
        if (stats.brokenCount == 0 && stats.needsRepairCount == 0) {
            sb.appendLine("  ✅ All assets are in working condition. Great job!")
        }
        sb.appendLine()
        sb.appendLine("Generated by Namma-Shaale Inventory App")
        sb.appendLine("Digital Asset Auditor for Schools")

        return sb.toString()
    }
}
